[tool.black]
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.tox
  | \.venv
  | \.vscode
  | \.eggs
  | _build
  | buck-out
  | build
  | dist
  | docs
)/
'''

[tool.isort]
profile = "black"

[tool.ruff]
line-length = 88
extend-exclude = [
    "docs",
]

[tool.ruff.per-file-ignores]
"__init__.py" = ["E402", "F401", "F403"]
