name: Python flake8 check

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Lint with flake8
      run: |
        pip install flake8
        # W503 - binary expression before line break
        # E402 - import order
        flake8 . --count --exclude=docs,validate --ignore=E402,W503 --max-line-length=100 --show-source --statistics
